name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: win

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and build
        run: |
          python3 -m pip install --break-system-packages setuptools
          npm install
          npm run postinstall
          npm run build

      - name: Publish releases
        env:
          # The APPLE_* values are used for auto updates signing
          # APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node release/app/fixSqlite3bug.js
          npm exec electron-builder -- --publish always --${{ matrix.platform }}
